spring:
  application:
    name: GearPC

  profiles:
    default: dev

  docker:
    compose:
      enabled: false

  # Cấu hình Flyway
  flyway:
    enabled: true  #Cho phép tự động chạy Flyway khi ứng dụng khởi động
    locations: classpath:db/migration
    baseline-on-migrate: false #true: sẽ tạo bảng flyway_schema_history nếu chưa tồn tại, \
    #false: báo lỗi nếu db đã có dữ liệu nhưng chưa có bảng flyway_schema_history
    baseline-version: 1

  # Cấu hình JPA / Hibernate
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  data:
    web:
      pageable:
        one-indexed-parameters: true

server:
  port: ${SERVER_PORT:8086}
